# Generated by Django 2.2.16 on 2023-04-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории.', max_length=200, verbose_name='Название.')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Напишите описание категории.', verbose_name='Описание.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Введите текст поста', max_length=200, verbose_name='Текст поста')),
                ('description', models.TextField(help_text='Напишите описание товара.', verbose_name='Описание.')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Картинка')),
                ('category', models.ForeignKey(blank=True, help_text='Категория, товара.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Category', verbose_name='Категория.')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
                'default_related_name': 'products',
            },
        ),
    ]
