# Generated by Django 2.2.16 on 2023-04-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230429_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Напишите описание товара', null=True, verbose_name='Описание'),
        ),
    ]
