# Generated by Django 2.2.16 on 2023-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Напишите ссылку (только на английском)', unique=True, verbose_name='Ссылка'),
        ),
    ]
