# Generated by Django 2.2.16 on 2023-05-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230501_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Закупочная цена'),
        ),
    ]
